apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ontheair-ingress
spec:
    rules:
      - host: kub-api.com
        http:
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rollout-bluegreen-active
                port:
                  number: 80